import { describe, it, expect } from "vitest";
import { Buffer } from "buffer";
// @abaplint/core initialises built-in symbols via Buffer.from(..., "hex"), the
// same reason src/workers/abaplintWorker.ts polyfills it before importing.
(globalThis as unknown as { Buffer: typeof Buffer }).Buffer = Buffer;

import { Registry, MemoryFile, Config } from "@abaplint/core";
import { Transpiler, config as transpilerConfig } from "@abaplint/transpiler";
import { prepareTranspiledJs } from "../utils/prepareTranspiledJs";
// Same `?raw` route executor.test.ts uses; the bundle is a global-scope IIFE
// that cannot be imported as a module.
import bundleSource from "./runtime-bundle.js?raw";

/**
 * runtime-bundle.js is a committed build artifact, so npm can bump
 * @abaplint/transpiler without the runtime it emits calls into moving with it.
 * That asymmetry is not theoretical: the transpiler learned to emit
 * `abap.statements.skip()` while the bundle in the repo predated the statement,
 * which would have turned a clean transpile_error into a runtime crash.
 *
 * These tests transpile and then execute, so a bundle that has fallen behind
 * the transpiler fails here rather than in the sandbox.
 * Run `node scripts/build-runtime-bundle.mjs` to refresh it.
 */

interface AbapRuntime {
  ABAP: new (options: { console: Streamer }) => unknown;
}

interface Streamer {
  add(text: string): void;
  clear(): void;
  isEmpty(): boolean;
  get(): string;
}

function loadRuntime(): AbapRuntime {
  return new Function(`${bundleSource}\nreturn abaplintRuntime;`)() as AbapRuntime;
}

async function transpile(source: string): Promise<string> {
  const reg = new Registry(new Config(JSON.stringify(transpilerConfig)));
  reg.addFile(new MemoryFile("ztest.prog.abap", source));
  await reg.parseAsync();
  const errors = reg
    .findIssues()
    .filter((i) => i.getSeverity().toString() === "Error");
  expect(errors.map((e) => e.getMessage())).toEqual([]);

  const output = await new Transpiler({ ignoreSourceMap: true }).run(reg);
  return [
    ...output.objects.map((o) => o.chunk.getCode()),
    output.initializationScript,
    output.initializationScript2,
  ].join("\n");
}

async function run(source: string): Promise<string> {
  let buffer = "";
  const streamer: Streamer = {
    add: (text) => {
      buffer += text;
    },
    clear: () => {
      buffer = "";
    },
    isEmpty: () => buffer.length === 0,
    get: () => buffer,
  };

  const js = prepareTranspiledJs(await transpile(source));
  const abap = new (loadRuntime().ABAP)({ console: streamer });
  const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
  await new AsyncFunction("abap", js)(abap);
  return buffer;
}

describe("runtime-bundle.js keeps up with the transpiler", () => {
  it("names the @abaplint/runtime it was built from", () => {
    expect(bundleSource).toMatch(
      /^\/\/ Generated by scripts\/build-runtime-bundle\.mjs from @abaplint\/runtime@\d+\.\d+\.\d+\./,
    );
  });

  it("runs WRITE, the shape every other statement builds on", async () => {
    expect(await run("WRITE 'a'.\nWRITE / 'b'.")).toBe("a\nb");
  });

  it("runs SKIP, which the transpiler emits as abap.statements.skip()", async () => {
    expect(await run("WRITE 'a'.\nSKIP.\nWRITE 'b'.")).toBe("a\nb");
  });

  it("runs SKIP n", async () => {
    expect(await run("WRITE 'a'.\nSKIP 2.\nWRITE 'b'.")).toBe("a\n\nb");
  });
});
